### ISSUE TITLE
Docker Container Has Some Issues.

### ISSUE THREAD

**Issue by swapxs** [scottlepp/loki-mcp#1]
Correct me if I am wrong but I have pulled the repo to be used for my project with the following compose.

```yml
# Other configs
  loki-mcp:
    build:
      context: https://github.com/scottlepp/loki-mcp.git # Correct repo
    container_name: loki-mcp
    environment:
      LOKI_URL: http://loki:3100
    depends_on:
      - loki
    restart: unless-stopped
# Other configs
```

But all I get is the container getting stuck in restart over and over and with no logs to debug it.

Some help will be appreciated.
Thanks
